### ISSUE TITLE
Find a tutorial to follow for human facial keypoint detection

### ISSUE THREAD

**Issue by niccolovettorello1997** [niccolovettorello1997/VCS#29]
- https://debuggercafe.com/getting-started-with-facial-keypoint-detection-using-pytorch/
- https://www.analyticsvidhya.com/blog/2021/07/face-key-point-recognition-using-cnn/
- https://medium.com/gazicyber/facial-keypoints-detection-using-tensorflow-in-google-colab-62e4db53561a

**Comment by eltonsst** [comment]
i primi due link non mi piacciono molto.
l'ultimo usa sempre lo stesso dataset di kaggle e fa una cnn semplice (la famosa baseline), io direi che possiamo guardare qui per la baseline e poi dall'altro link per la "inception like" network per lo sviluppo. Per la relazione seguiamo il paper.
